version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - app-network

  client:
    build:
      context: ./client  # Контекст сборки - папка client
      dockerfile: Dockerfile  # ⚠️ Исправлено! Просто имя файла, без пути
    networks:
      - app-network
    # Убрал том сборки, так как он не нужен для работы приложения
    # (сборка происходит внутри контейнера, результат копируется в nginx)

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Используем том из клиентского сервиса:
      - client_build:/usr/share/nginx/html:ro
    networks:
      - app-network
    depends_on:
      - client

volumes:
  portainer_data:
    driver: local
  client_build:  # ⚠️ Новый именованный том для сборки

networks:
  app-network:
    driver: bridge