version: '3.8'

services:
  # Frontend builder
  frontend-builder:
    build: 
      context: ./client
      dockerfile: Dockerfile
    networks:
      - portainer-network
    volumes:
      - frontend-build:/app/build

  # Frontend server
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend-build:/usr/share/nginx/html:ro
    networks:
      - portainer-network
    depends_on:
      - frontend-builder

  # Portainer API service
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - portainer-network

networks:
  portainer-network:
    driver: bridge

volumes:
  frontend-build:
  portainer-data: