version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - app-network

  client:
    build: ./client
    networks:
      - app-network
    # Добавьте эту секцию, если нужно сохранить собранные файлы
    volumes:
      - ./client/build:/app/build

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - client

networks:
  app-network:
    driver: bridge