version: '3.8'

services:
  client:
    build: ./client
    networks:
      - app-network
    # Добавьте эту секцию, если нужно сохранить собранные файлы
    volumes:
      - ./client/build:/app/build

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - client

networks:
  app-network:
    driver: bridge