version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - portainer-network
    volumes:
      - frontend-build:/app/build
      - nginx-config:/nginx-config

  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-config:/etc/nginx/conf.d
    networks:
      - portainer-network
    depends_on:
      - frontend

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - portainer-network

networks:
  portainer-network:
    driver: bridge

volumes:
  frontend-build:
  portainer-data:
  nginx-config: