version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - app-network

  client: # ПЕРЕМЕЩЕНО В РАЗДЕЛ SERVICES
    build:
      context: ./client # 🔴 КРИТИЧЕСКОЕ ИЗМЕНЕНИЕ!
      dockerfile: Dockerfile # Путь относительно корня
    networks:
      - app-network
    volumes:
      - ./client/build:/app/build # bind mount (не требует объявления в volumes)

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html # использует сборку из client
    networks:
      - app-network
    depends_on:
      - client

volumes:
  portainer_data: # ТОЛЬКО ОПРЕДЕЛЕНИЕ ТОМА (без лишних свойств)
    driver: local

networks:
  app-network:
    driver: bridge
